
config {
      type:"view",
      schema:'staging',
      description: 'A sample GA Sessions staging table'
  }

SELECT 
 Count(visitId) as Visitors,
Count(totals.pageviews) as totalPageviews,
SUM(totals.timeOnsite) as timeonSite,
trafficSource.source
FROM 
 ${ref("ga_sessions_20170801")}
WHERE
  totals.timeOnSite IS NOT NULL 
  and trafficSource.source != '(direct)'
group by trafficSource.source



